// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/steamgame/steamgamepb/steamgame.proto

package steamgamepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameSearch struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameSearch) Reset()         { *m = GameSearch{} }
func (m *GameSearch) String() string { return proto.CompactTextString(m) }
func (*GameSearch) ProtoMessage()    {}
func (*GameSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_steamgame_a2592ad2a1e9adeb, []int{0}
}
func (m *GameSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSearch.Unmarshal(m, b)
}
func (m *GameSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSearch.Marshal(b, m, deterministic)
}
func (dst *GameSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSearch.Merge(dst, src)
}
func (m *GameSearch) XXX_Size() int {
	return xxx_messageInfo_GameSearch.Size(m)
}
func (m *GameSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSearch.DiscardUnknown(m)
}

var xxx_messageInfo_GameSearch proto.InternalMessageInfo

func (m *GameSearch) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type SearchGameRequest struct {
	Search               *GameSearch `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchGameRequest) Reset()         { *m = SearchGameRequest{} }
func (m *SearchGameRequest) String() string { return proto.CompactTextString(m) }
func (*SearchGameRequest) ProtoMessage()    {}
func (*SearchGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_steamgame_a2592ad2a1e9adeb, []int{1}
}
func (m *SearchGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchGameRequest.Unmarshal(m, b)
}
func (m *SearchGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchGameRequest.Marshal(b, m, deterministic)
}
func (dst *SearchGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchGameRequest.Merge(dst, src)
}
func (m *SearchGameRequest) XXX_Size() int {
	return xxx_messageInfo_SearchGameRequest.Size(m)
}
func (m *SearchGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchGameRequest proto.InternalMessageInfo

func (m *SearchGameRequest) GetSearch() *GameSearch {
	if m != nil {
		return m.Search
	}
	return nil
}

type Game struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_steamgame_a2592ad2a1e9adeb, []int{2}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (dst *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(dst, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Game) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type SearchGameResponse struct {
	Games                []*Game  `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchGameResponse) Reset()         { *m = SearchGameResponse{} }
func (m *SearchGameResponse) String() string { return proto.CompactTextString(m) }
func (*SearchGameResponse) ProtoMessage()    {}
func (*SearchGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_steamgame_a2592ad2a1e9adeb, []int{3}
}
func (m *SearchGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchGameResponse.Unmarshal(m, b)
}
func (m *SearchGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchGameResponse.Marshal(b, m, deterministic)
}
func (dst *SearchGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchGameResponse.Merge(dst, src)
}
func (m *SearchGameResponse) XXX_Size() int {
	return xxx_messageInfo_SearchGameResponse.Size(m)
}
func (m *SearchGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchGameResponse proto.InternalMessageInfo

func (m *SearchGameResponse) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

type GameDetailsRequest struct {
	Game                 *Game    `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameDetailsRequest) Reset()         { *m = GameDetailsRequest{} }
func (m *GameDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GameDetailsRequest) ProtoMessage()    {}
func (*GameDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_steamgame_a2592ad2a1e9adeb, []int{4}
}
func (m *GameDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameDetailsRequest.Unmarshal(m, b)
}
func (m *GameDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameDetailsRequest.Marshal(b, m, deterministic)
}
func (dst *GameDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameDetailsRequest.Merge(dst, src)
}
func (m *GameDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GameDetailsRequest.Size(m)
}
func (m *GameDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameDetailsRequest proto.InternalMessageInfo

func (m *GameDetailsRequest) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type GameDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameDetails) Reset()         { *m = GameDetails{} }
func (m *GameDetails) String() string { return proto.CompactTextString(m) }
func (*GameDetails) ProtoMessage()    {}
func (*GameDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_steamgame_a2592ad2a1e9adeb, []int{5}
}
func (m *GameDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameDetails.Unmarshal(m, b)
}
func (m *GameDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameDetails.Marshal(b, m, deterministic)
}
func (dst *GameDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameDetails.Merge(dst, src)
}
func (m *GameDetails) XXX_Size() int {
	return xxx_messageInfo_GameDetails.Size(m)
}
func (m *GameDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_GameDetails.DiscardUnknown(m)
}

var xxx_messageInfo_GameDetails proto.InternalMessageInfo

func (m *GameDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GameDetails) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GameDetails) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GameDetailsResponse struct {
	Details              *GameDetails `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GameDetailsResponse) Reset()         { *m = GameDetailsResponse{} }
func (m *GameDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GameDetailsResponse) ProtoMessage()    {}
func (*GameDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_steamgame_a2592ad2a1e9adeb, []int{6}
}
func (m *GameDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameDetailsResponse.Unmarshal(m, b)
}
func (m *GameDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameDetailsResponse.Marshal(b, m, deterministic)
}
func (dst *GameDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameDetailsResponse.Merge(dst, src)
}
func (m *GameDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GameDetailsResponse.Size(m)
}
func (m *GameDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameDetailsResponse proto.InternalMessageInfo

func (m *GameDetailsResponse) GetDetails() *GameDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*GameSearch)(nil), "steam_game.GameSearch")
	proto.RegisterType((*SearchGameRequest)(nil), "steam_game.SearchGameRequest")
	proto.RegisterType((*Game)(nil), "steam_game.Game")
	proto.RegisterType((*SearchGameResponse)(nil), "steam_game.SearchGameResponse")
	proto.RegisterType((*GameDetailsRequest)(nil), "steam_game.GameDetailsRequest")
	proto.RegisterType((*GameDetails)(nil), "steam_game.GameDetails")
	proto.RegisterType((*GameDetailsResponse)(nil), "steam_game.GameDetailsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SteamGameServiceClient is the client API for SteamGameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SteamGameServiceClient interface {
	SearchGame(ctx context.Context, in *SearchGameRequest, opts ...grpc.CallOption) (*SearchGameResponse, error)
	GameDetails(ctx context.Context, in *GameDetailsRequest, opts ...grpc.CallOption) (*GameDetailsResponse, error)
}

type steamGameServiceClient struct {
	cc *grpc.ClientConn
}

func NewSteamGameServiceClient(cc *grpc.ClientConn) SteamGameServiceClient {
	return &steamGameServiceClient{cc}
}

func (c *steamGameServiceClient) SearchGame(ctx context.Context, in *SearchGameRequest, opts ...grpc.CallOption) (*SearchGameResponse, error) {
	out := new(SearchGameResponse)
	err := c.cc.Invoke(ctx, "/steam_game.SteamGameService/SearchGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steamGameServiceClient) GameDetails(ctx context.Context, in *GameDetailsRequest, opts ...grpc.CallOption) (*GameDetailsResponse, error) {
	out := new(GameDetailsResponse)
	err := c.cc.Invoke(ctx, "/steam_game.SteamGameService/GameDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamGameServiceServer is the server API for SteamGameService service.
type SteamGameServiceServer interface {
	SearchGame(context.Context, *SearchGameRequest) (*SearchGameResponse, error)
	GameDetails(context.Context, *GameDetailsRequest) (*GameDetailsResponse, error)
}

func RegisterSteamGameServiceServer(s *grpc.Server, srv SteamGameServiceServer) {
	s.RegisterService(&_SteamGameService_serviceDesc, srv)
}

func _SteamGameService_SearchGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamGameServiceServer).SearchGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steam_game.SteamGameService/SearchGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamGameServiceServer).SearchGame(ctx, req.(*SearchGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SteamGameService_GameDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamGameServiceServer).GameDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steam_game.SteamGameService/GameDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamGameServiceServer).GameDetails(ctx, req.(*GameDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SteamGameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "steam_game.SteamGameService",
	HandlerType: (*SteamGameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchGame",
			Handler:    _SteamGameService_SearchGame_Handler,
		},
		{
			MethodName: "GameDetails",
			Handler:    _SteamGameService_GameDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/steamgame/steamgamepb/steamgame.proto",
}

func init() {
	proto.RegisterFile("service/steamgame/steamgamepb/steamgame.proto", fileDescriptor_steamgame_a2592ad2a1e9adeb)
}

var fileDescriptor_steamgame_a2592ad2a1e9adeb = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x69, 0x5a, 0xed, 0x04, 0xa5, 0x8e, 0x52, 0x43, 0xc1, 0x5a, 0x42, 0x91, 0x1e, 0x34,
	0x62, 0xbd, 0x89, 0x27, 0x15, 0x14, 0x04, 0x0f, 0xe9, 0xcd, 0x8b, 0xa4, 0xdb, 0x41, 0x17, 0xfa,
	0x11, 0x77, 0xb7, 0x82, 0xbf, 0xca, 0xbf, 0x28, 0xfb, 0x91, 0x26, 0x6d, 0xe9, 0x6d, 0xe6, 0xcd,
	0x9b, 0xb7, 0x6f, 0x66, 0x07, 0xae, 0x24, 0x89, 0x1f, 0xce, 0xe8, 0x5a, 0x2a, 0xca, 0x66, 0x9f,
	0xd9, 0xac, 0x12, 0xe5, 0xe3, 0x32, 0x4e, 0x72, 0xb1, 0x50, 0x0b, 0x04, 0x03, 0x7c, 0x68, 0x24,
	0xee, 0x03, 0x3c, 0x67, 0x33, 0x1a, 0x51, 0x26, 0xd8, 0x17, 0xb6, 0xa1, 0x21, 0x4d, 0x14, 0x79,
	0x3d, 0x6f, 0xd0, 0x4c, 0x5d, 0x16, 0x3f, 0xc2, 0x91, 0x65, 0x68, 0x6e, 0x4a, 0xdf, 0x4b, 0x92,
	0x0a, 0x93, 0x35, 0x72, 0x38, 0x6c, 0x27, 0xa5, 0x6e, 0x52, 0x8a, 0xae, 0x44, 0x2e, 0x21, 0xd0,
	0x28, 0x1e, 0x82, 0xcf, 0x27, 0xee, 0x01, 0x9f, 0x4f, 0xf0, 0x04, 0xea, 0x8a, 0xab, 0x29, 0x45,
	0xbe, 0x81, 0x6c, 0x12, 0xdf, 0x03, 0x56, 0x9f, 0x94, 0xf9, 0x62, 0x2e, 0x09, 0x2f, 0xa0, 0xae,
	0xe5, 0x65, 0xe4, 0xf5, 0x6a, 0x83, 0x70, 0xd8, 0xda, 0x7c, 0x32, 0xb5, 0xe5, 0xf8, 0x0e, 0x50,
	0xa7, 0x4f, 0xa4, 0x32, 0x3e, 0x95, 0x85, 0xe3, 0x3e, 0x04, 0xba, 0xec, 0xfc, 0x6e, 0x37, 0x9b,
	0x6a, 0xcc, 0x20, 0xac, 0xf4, 0x22, 0x42, 0x30, 0x2f, 0x9a, 0x9a, 0xa9, 0x89, 0xdd, 0x08, 0xfe,
	0x6a, 0x84, 0x0e, 0xec, 0xb3, 0xa5, 0x10, 0x34, 0x67, 0xbf, 0x51, 0xcd, 0xa0, 0xab, 0x5c, 0x8f,
	0x97, 0x0b, 0xce, 0x28, 0x0a, 0x7a, 0xde, 0xc0, 0x4b, 0x6d, 0x12, 0xbf, 0xc0, 0xf1, 0x9a, 0x41,
	0x37, 0xdf, 0x0d, 0xec, 0x4d, 0x2c, 0xe4, 0x4c, 0x9e, 0x6e, 0x9a, 0x2c, 0x3a, 0x0a, 0xde, 0xf0,
	0xcf, 0x83, 0xd6, 0x48, 0x73, 0xec, 0xca, 0xcd, 0x21, 0xe0, 0x2b, 0x40, 0xb9, 0x3d, 0x3c, 0xab,
	0x8a, 0x6c, 0x7d, 0x64, 0xa7, 0xbb, 0xab, 0xec, 0x4c, 0xbd, 0xad, 0x2f, 0xa4, 0xbb, 0xcb, 0x92,
	0x93, 0x3b, 0xdf, 0x59, 0xb7, 0x7a, 0x0f, 0x07, 0xef, 0x61, 0xe5, 0x3c, 0xc7, 0x0d, 0x73, 0x95,
	0xb7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xd8, 0x22, 0x16, 0xc6, 0x02, 0x00, 0x00,
}
